# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20,1.21)
forge_version=47.4.6
loader_version_range=[46,)
mapping_channel=official
mapping_version=1.20.1

create_version = 6.0.6-150
ponder_version = 1.0.80
flywheel_version = 1.0.4
registrate_version = MC1.20-1.3.3

mod_id=some_assembly_required
mod_name=Some Assembly Required
mod_license=MIT
mod_version=1.20.1-4.2.1
mod_group_id=some-assembly-required
mod_authors=ochotonida
mod_credits=Based on the fabric mod 'Sandwichable' by FoundationGames
mod_description=Design your own sandwiches!
